[tool.poetry]
name = "astal"
version = "0.1.0"
description = ""
authors = [{ name = "natalie roentgen connolly", email = "natalie@natalieee.net" }]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
